@86eqdzrf4#waiting-for-device-approval
NCLEXPower/nclexpower_turbo pull request #400
Opened 2024-10-24 11:56 UTC by SamuelJavier

Desktop View: 
![image](https://github.com/user-attachments/assets/ab3eb217-4b3f-4a32-ba98-a35fdcacbc86)

Mobile View:
![image](https://github.com/user-attachments/assets/78123890-9b62-497b-b49b-b10a86e52800)

2024-10-25 05:51 UTC, JezChristian commented
The design is great but I think you misunderstood the idea, this is for the requester, so it should look like it is waiting to be approved, rather than approving the request.

2024-10-25 06:00 UTC, JezChristian requested changes
I noticed that you referenced your work almost similar to the DeviceAccessDetection.tsx, is it not possible to reuse that?

2024-10-25 07:52 UTC, JMSevilla approved these changes

2024-10-25 09:36 UTC, JMSevilla requested changes
Please address comments

2024-10-31 08:52 UTC, BryanPalad approved these changes

2024-11-02 11:07 UTC, acostales08 approved these changes

2024-11-03 13:14 UTC, closed without merging