@86eqdaxxn #Custom-Delete-Modal-with-Typing
NCLEXPower/nclexpower_turbo pull request #401
Opened 2024-10-24 16:15 UTC by acostales08

2024-11-02 17:26 UTC, JMSevilla requested changes

2024-11-02 17:26 UTC, JMSevilla commented on packages/core-library/components/Dialog/DialogFormBlocks/deleteModal/deleteConfirmationBlock.tsx
> +export type delConType = {
Did you use this to your nested implementation ? please add this to the file where you are using it, or much better to add this on a types file. 

Also please use appropriate name of types. 

fyi, address the comments immediately.

2024-11-02 17:26 UTC, JMSevilla commented on packages/core-library/components/Dialog/DialogFormBlocks/deleteModal/deleteConfirmationForm.tsx
> +import { ControlledTextField } from "../../../Textfield/TextField";
Use our TextField instead of ControlledTextField from our component. 

`ControlledTextField` will soon to deprecate.

2024-11-02 17:26 UTC, JMSevilla commented on packages/core-library/contexts/DialogContext.tsx
> +  const [data, setData] = useState<any>(null);
remove <any>

2024-11-02 17:26 UTC, JMSevilla commented on packages/core-library/tests/components/Dialog/deleteConfirmationBlock.test.tsx
> +import { render } from "@testing-library/react";
render should be from common.

2024-11-03 10:11 UTC, JMSevilla approved these changes

2024-11-03 12:05 UTC, BryanPalad approved these changes

2024-11-03 13:08 UTC, JezChristian approved these changes

2024-11-03 13:08 UTC, DropitupQwerty approved these changes

2024-11-05 13:33 UTC, JezChristian requested changes

2024-11-05 13:33 UTC, JezChristian commented on packages/core-library/components/Dialog/DialogFormBlocks/deleteModal/deleteConfirmationForm.tsx
> +import { TextField } from "../../../forms/TextField";
Direct import of component

2024-11-05 13:33 UTC, JezChristian commented on packages/core-library/system/app/internal/blocks/Hub/Product/InclusionBlock.tsx
> +import { CustomPopover } from "../../../../../../components/Popover/Popover";
Direct import of component

2024-11-11 08:27 UTC, closed without merging