Feature/86eqctme8 wb setting content isolation
NCLEXPower/nclexpower_turbo pull request #410
Opened 2024-10-29 03:39 UTC by nasolgabriel

Different Content rendered based on Access level
**IMPROVED OVERALL IMPLEMENTATION**

**Admin :** 
- Can Access All Configurations
![image](https://github.com/user-attachments/assets/55c0896f-e606-4521-85ca-28bc6a69b205)

**Encoder :** 
- Web Simulator
![image](https://github.com/user-attachments/assets/e40dab1a-0b03-45d1-92ae-df1660fdbe85)

**Developer :** 
- In App Router Management
- DB & Excel Comparison
![image](https://github.com/user-attachments/assets/f72b3d49-3b70-41d8-b75e-aee31fb3227b)

2024-10-29 04:19 UTC, be3jaay requested changes

2024-10-29 04:19 UTC, be3jaay commented on packages/core-library/components/AccessControl/AccessControl.tsx
> +  children: React.ReactNode;
```suggestion

```
Remove this

2024-10-29 04:19 UTC, be3jaay commented on packages/core-library/components/AccessControl/AccessControl.tsx
> +export const AccessControl: React.FC<AccessControlProps> = ({ componentName, children }) => {
```suggestion
export const AccessControl: React.FC<React.PropsWithChildren<AccessControlProps>> = ({ componentName, children }) => {
```

2024-10-29 05:50 UTC, BryanPalad requested changes

2024-10-31 08:48 UTC, BryanPalad approved these changes

2024-11-02 17:17 UTC, JMSevilla requested changes

2024-11-02 17:17 UTC, JMSevilla commented on packages/core-library/hooks/useAccessControl.ts
> +export const useAccessControl = () => {
Suggestion please address this immediately since we are now preparing for next sprint 

1. RBAC Model Centralizing permissions, create this functionality under core-library/utils
// permissions.ts
export const AccessLevels = {
  ADMIN: 0,
  EDITOR: 1,
  VIEWER: 2,
};

export const accessControl = {
  [AccessLevels.ADMIN]: [
    'ChooseProductsConfigurations',
    'OtherConfigurations',
    'ContentManagementSystemSettings',
    'InAppManagement',
  ],
  [AccessLevels.EDITOR]: ['ChooseProductsConfigurations'],
  [AccessLevels.VIEWER]: ['InAppManagement', 'OtherConfigurations'],
};

export const canAccess = (accessLevel: number, component: string): boolean => {
  return accessControl[accessLevel]?.includes(component);
};

2. Create custom hook for access control under hooks folder in core-library

// useAccessControl.ts
import { useState, useEffect } from 'react';
import { canAccess, AccessLevels } from 'your permissions path.';

export const useAccessControl = () => {
  const [accessLevel, setAccessLevel] = useState<number | null>(null);

  useEffect(() => {
    const userAccessLevel = sessionStorage.getItem('al');
    setAccessLevel(Number(userAccessLevel));
  }, []);

  const hasAccess = (component: string): boolean => {
    if (accessLevel === null) return false; // No access level set yet
    return canAccess(accessLevel, component);
  };

  return { accessLevel, hasAccess };
};

3. Usage example

{hasAccess('ChooseProductsConfigurations') && (
        <ChooseProductsConfigurations nextStep={nextStep} values={values} />
      )}

2024-11-03 15:06 UTC, be3jaay approved these changes

2024-11-05 14:45 UTC, closed without merging