@86eqan2m5 #Modify ControlledAccordion Component
NCLEXPower/nclexpower_turbo pull request #413
Opened 2024-10-29 15:55 UTC by BryanPalad

2024-10-30 07:52 UTC, JMSevilla requested changes

2024-10-30 07:52 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/ProgramListBlock.tsx
> +                  {item.sections?.length ?? 0} Sections
is it given that if sections is empty , length should be 0 ? so I guess `?? 0` is not necessary.

2024-10-30 07:52 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/ProgramListBlock.tsx
> +          {(sections ?? []).length > 0 ? (
Instead of using (sections ?? []) twice, we can simplify to a single sections?.length > 0 check for cleaner code and reduced redundancy.

2024-10-30 07:52 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/ProgramListBlock.tsx
> +                      src={getSectionTypeIcons(sectionType)}
Consider adding a fallback icon to prevent issues if these functions return undefined.

src={getSectionTypeIcons(sectionType) || fallbackIcon}

2024-10-30 07:52 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/ProgramListBlock.tsx
> +                      onClick={
Instead of a ternary, use a short-circuit for onClick.

onClick={() => hasVideos && handleShowVideos(sectionVideos, id)}

2024-10-30 07:52 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/ProgramListBlock.tsx
> +                    src={getSectionStatusIcons(sectionStatus)}
Consider adding a fallback icon to prevent issues if these functions return undefined.

src={getSectionTypeIcons(sectionType) || fallbackIcon}

2024-10-30 07:52 UTC, JMSevilla commented on apps/web-customer/src/pages/shared/Page.tsx
> +  // if (data?.loadMaintenanceMode?.maintenanceModeType === 1) {
Uncomment this back as our production currently connected with our checked out branch

2024-10-30 07:52 UTC, JMSevilla commented on packages/core-library/components/Accordion/CustomAccordionSummary.tsx
> +import { AccordionSummary } from "@mui/material";
import { styled } here.

2024-10-30 08:20 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/ProgramListBlock.tsx
> +                      src={getSectionTypeIcons(sectionType)}
![image](https://github.com/user-attachments/assets/d4eecbda-45b1-4770-bd7d-cf1b5ea84cc9)
fallBackIcons are already implemented inside the IconUtils of the function getSectionTypeIcons etc...

2024-10-30 08:29 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/ProgramListBlock.tsx
> +                      onClick={
Noted

2024-10-30 08:30 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/ProgramListBlock.tsx
> +                    src={getSectionStatusIcons(sectionStatus)}
![image](https://github.com/user-attachments/assets/fec53674-a989-485e-ba03-ba60e77401c8)

fallBackIcons are already implemented inside the IconUtils of the function getSectionTypeIcons etc...

2024-10-30 08:31 UTC, BryanPalad commented on apps/web-customer/src/pages/shared/Page.tsx
> +  // if (data?.loadMaintenanceMode?.maintenanceModeType === 1) {
Will revert the changes for this immediately.

2024-10-30 08:37 UTC, BryanPalad commented on packages/core-library/components/Accordion/CustomAccordionSummary.tsx
> +import { AccordionSummary } from "@mui/material";
Already imported {styled} from "@mui/material" in line 8.

2024-10-30 08:47 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/HubBlocks/ProgramListBlock/ProgramListBlock.tsx
> +          {(sections ?? []).length > 0 ? (
Noted

2024-10-31 08:43 UTC, JMSevilla approved these changes

2024-10-31 14:09 UTC, DropitupQwerty approved these changes

2024-10-31 16:32 UTC, JezChristian approved these changes

2024-10-31 16:32 UTC, merged