@86eqkvzy7 #Inclusion list Api Integration
NCLEXPower/nclexpower_turbo pull request #417
Opened 2024-11-04 12:37 UTC by be3jaay

2024-11-04 13:01 UTC, BryanPalad approved these changes

2024-11-04 14:08 UTC, acostales08 approved these changes

2024-11-04 16:24 UTC, JezChristian requested changes

2024-11-04 16:24 UTC, JezChristian commented on packages/core-library/system/app/internal/blocks/Hub/Product/products/ProductForm.tsx
>  import { GenericSelectField } from "core-library/components/Textfield/GenericSelectField";
Component  has been directly imported

2024-11-04 16:24 UTC, JezChristian commented on packages/core-library/system/app/internal/blocks/Hub/Product/products/ProductForm.tsx
> +  const inclusions = inclusionsData?.map((item: GetInternalInclusionsType) => ({
Maybe we can add inclusionsData.length > 0 && for safety of rendering

2024-11-05 13:11 UTC, JezChristian approved these changes

2024-11-07 06:06 UTC, merged