@86eq301wd #Multiple-Contents-Approval-Rejections
NCLEXPower/nclexpower_turbo pull request #418
Opened 2024-11-04 14:07 UTC by acostales08

2024-11-05 13:31 UTC, JezChristian requested changes

2024-11-05 13:31 UTC, JezChristian commented on packages/core-library/components/Dialog/DialogFormBlocks/contentApproval/ApprovalDialogForm.tsx
> +import { Button } from "../../../Button/Button";
Direct Import of Component

2024-11-05 13:31 UTC, JezChristian commented on packages/core-library/components/Dialog/DialogFormBlocks/contentApproval/ApprovalDialogForm.tsx
> +import { DateField } from "../../../forms/datefield/DateField";
Is this a Component? If that the case direct import of component

2024-11-05 13:31 UTC, JezChristian commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/steps/content/regular/ApprovalListView.tsx
> +import { CustomPopover } from "../../../../../../../../../../components/Popover/Popover";
Direct import

2024-11-05 13:31 UTC, JezChristian commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/steps/content/regular/ApprovalListViewBlock.tsx
> +import { CustomPopover } from "../../../../../../../../../../components/Popover/Popover";
Direct import

2024-11-05 13:31 UTC, JezChristian commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/steps/content/regular/ApprovalListViewBlock.tsx
> +  const actionButtons = [
Isolate this

2024-11-13 14:57 UTC, JezChristian requested changes

2024-11-13 14:57 UTC, JezChristian commented on packages/core-library/components/index.ts
>  // rows
Remove comment

2024-11-13 14:57 UTC, JezChristian commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/steps/content/regular/ApprovalListViewBlock.tsx
> +type ToastType = "info" | "success" | "error" | "warning";
Isolate this and make it global so this can be used by other files

2024-11-13 14:57 UTC, JezChristian commented on packages/core-library/system/app/internal/blocks/Hub/content/approval/steps/content/regular/ApprovalListViewBlock.tsx
> +  const renderActionButtons = (contentId: string, contentAuthorId: string) =>
when using const, Capitalize the first letter
use small letter if it is a function

example : 
const RenderActionButtons = () => {}

function renderActionButton() {}

2024-11-14 10:28 UTC, BryanPalad requested changes

2024-11-14 10:28 UTC, BryanPalad commented on packages/core-library/components/Dialog/DialogFormBlocks/contentApproval/ApprovalDialogBlock.tsx
> +      console.log("onSubmit", values);
Remove console

2024-11-14 10:28 UTC, BryanPalad commented on packages/core-library/components/Dialog/DialogFormBlocks/contentApproval/ApprovalDialogBlock.tsx
> +      toast.executeToast("Successfully submitted..", "top-right", false, {
You can use this instead `const { showToast } = useExecuteToast();` 

`showToast("Successfully submitted.", "success");`

2024-11-14 10:28 UTC, BryanPalad commented on packages/core-library/components/Dialog/DialogFormBlocks/contentApproval/ApprovalDialogBlock.tsx
> +      console.error("Something wrong", err);
You can also use the `showToast("Something went wrong.", "error");` instead of console

2024-11-14 10:28 UTC, BryanPalad commented on packages/core-library/components/Dialog/DialogFormBlocks/contentApproval/ApprovalDialogBlock.tsx
> +      setContentLoader(true);
I think it's better if we put the `setContentLoader(true)` at the top of try catch since you already have the `setContentLoader(false);` below

2024-11-15 18:03 UTC, closed without merging