@86eqmv3bh #Delivery-board-request-Pricing-Management
NCLEXPower/nclexpower_turbo pull request #420
Opened 2024-11-05 15:24 UTC by acostales08

2024-11-06 11:51 UTC, JezChristian approved these changes

2024-11-07 04:40 UTC, BryanPalad approved these changes

2024-11-07 13:19 UTC, JMSevilla requested changes

2024-11-07 13:19 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Product/pricing/PricingForm.tsx
> +  console.log("has error message", sample);
remove

2024-11-08 12:53 UTC, DropitupQwerty approved these changes

2024-11-09 03:17 UTC, JMSevilla approved these changes

2024-11-09 10:57 UTC, merged