@86eqddgy1 #SalesManagement UI WB
NCLEXPower/nclexpower_turbo pull request #422
Opened 2024-11-06 10:04 UTC by LizterBabael

SalesManagement UI 

only mock data 

Tablet view:
![Screenshot 2024-11-05 204729](https://github.com/user-attachments/assets/a19893a6-cef6-4a28-a623-5f0a90746e59)

Iphone
![Screenshot 2024-11-05 204711](https://github.com/user-attachments/assets/cb7901cc-d5f2-4c8d-9bc8-cb33e9bf5f16)

2024-11-07 04:34 UTC, BryanPalad requested changes

2024-11-07 04:34 UTC, BryanPalad commented on packages/core-library/components/DynamicChart/DynamicChart.tsx
> +
remove spacing

2024-11-07 04:34 UTC, BryanPalad commented on packages/core-library/components/DynamicChart/DynamicChart.tsx
> +
remove spacing

2024-11-07 04:34 UTC, BryanPalad commented on packages/core-library/components/DynamicChart/DynamicChart.tsx
> +
remove spacing

2024-11-07 04:34 UTC, BryanPalad commented on packages/core-library/system/app/internal/blocks/Hub/SalesManagement/SalesManagementBlock.tsx
> +import { PNSale } from "./PN-Sale";
You can add an index.ts under Hub/SalesManagement folder and export those 3 Sales data

`import { AllSale, RNSale, PNSale } from 'Hub/SalesManagement'`

2024-11-07 04:36 UTC, BryanPalad commented
![image](https://github.com/user-attachments/assets/c8b7b3c3-50b4-412c-bd9d-b58a7e6daa25)

Can we add a padding or margin here to make the tabs aligned to the toggle and data below?

You can use the `useResolution `hook `isTablet`

2024-11-07 05:16 UTC, LizterBabael commented on packages/core-library/system/app/internal/blocks/Hub/SalesManagement/SalesManagementBlock.tsx
> +import { PNSale } from "./PN-Sale";
Already tried it but when I tried to import, it only do the specific location, I'll try later and investigate why it doesn't work on my side.

2024-11-07 13:17 UTC, BryanPalad approved these changes

2024-11-07 15:54 UTC, JMSevilla requested changes

2024-11-07 15:54 UTC, JMSevilla commented on apps/web-backoffice-generic/src/pages/hub/sm/sales-management.tsx
> +export default withAuth(SalesManagementPage);
remove `withAuth` please check some of our existing implementation when using `ParseBlocks`

2024-11-07 15:54 UTC, JMSevilla commented on packages/core-library/components/DynamicChart/DynamicChart.tsx
> +/**
Change folder name from `DynamicChart` to `charts`

then create another folder name it `generic` then place your component within the `generic` folder

2024-11-07 15:54 UTC, JMSevilla commented on packages/core-library/components/DynamicChart/DynamicChart.tsx
> +type ChartOptions = {
this can be isolated create another file within the `generic` folder name it `types.ts` or `chart.ts`

Define more specific types for the props, especially for dataSet, options, and type, so we have better type safety and readability.

interface BarChartOptions {}
interface LineChartOptions extends Omit<BarChartOptions, 'maxRevenue'> {}
interface GaugeChartOptions {}

export type ChartOptions = BarChartOptions | LineChartOptions | GaugeChartOptions;

2024-11-07 15:54 UTC, JMSevilla commented on packages/core-library/components/DynamicChart/DynamicChart.tsx
> +  dataSet: any;
Using any for dataSet can lead to runtime issues, as there’s no validation on its structure. Define a more specific type or generic interface for dataSet to ensure type safety.

e.g., { [key: string]: any }[]

2024-11-07 15:54 UTC, JMSevilla commented on packages/core-library/components/DynamicChart/DynamicChart.tsx
> +  type: "Bar" | "Line" | "Gauge" | string;
Why we have string in here?

2024-11-07 15:54 UTC, JMSevilla commented on packages/core-library/components/DynamicChart/DynamicChart.tsx
> +  switch (type) {
The implementation here is obviously heavy please consider `Modularizing Chart Components` each chart type’s logic can be split into separate components for better organization and readability.

final usage look
switch (type) {
    case "Bar":
      return <BarChartRenderer dataSet={dataSet} width={width} height={height} options={options as BarChartOptions} sx={sx} />;
    case "Line":
      return <LineChartRenderer dataSet={dataSet} width={width} height={height} options={options as LineChartOptions} sx={sx} />;
    case "Gauge":
      return <GaugeChartRenderer dataSet={dataSet} width={width} height={height} options={options as GaugeChartOptions} sx={sx} />;
    default:
      return <div>No chart type selected</div>;

2024-11-07 15:54 UTC, JMSevilla commented on packages/core-library/components/DynamicChart/DynamicChart.tsx
> +            sx={(theme) => ({
To handle the Gauge styles more cleanly, extract a utility function for sx styling. This keeps the Gauge component cleaner.

final usage i want

sx={(theme) => ({
          ...sx,
          ...getGaugeStyles(options, theme),
        })}

2024-11-07 16:15 UTC, be3jaay requested changes

2024-11-07 16:15 UTC, be3jaay commented on packages/core-library/system/app/internal/blocks/Hub/SalesManagement/All-Sale.tsx
> +  };
Create a reusable hook for these function const [selectedPeriod, setSelectedPeriod] = useState("all");, const handlePeriodChange = (event: React.ChangeEvent<HTMLInputElement>) => {,   const formatRevenue = (value: number) => { since this is being repeated on other pages such as all-sale, pn-sale, and rn-sale.

2024-11-09 03:15 UTC, JMSevilla requested changes

2024-11-09 03:15 UTC, JMSevilla commented on packages/core-library/components/Charts/generic/Chart.tsx
> +import { Barchart, Gaugechart, Linechart } from "./index";
It seems like the structure is wrong. 

inside your generic folder create another folder `charts` then all chart types such as your `bar chart, gauge chart, line chart , etc..` should be inside this folder. 

Then your `Chart.tsx` must be outside your `chart` folder

when importing please prevent defining `index` since react already understood if it is the root of your components.

2024-11-09 03:15 UTC, JMSevilla commented on packages/core-library/components/Charts/generic/LineChart/Linechart.tsx
> +export const Linechart: React.FC<LineChartProps> = ({
It should be `LineChart` not `Linechart`

2024-11-09 03:15 UTC, JMSevilla commented on packages/core-library/components/Charts/generic/Type.ts
> +export const getGaugeStyles = (options: GaugeChartOptions, theme: Theme) => {
instead of `getGaugeStyles` make it `useGaugeStyles`

2024-11-09 03:15 UTC, JMSevilla commented on packages/core-library/hooks/usePeriodTime.ts
> +export const usePeriodTime = <T>({
You should add comments above on this hook explaining the technicalities or usage of this code. Please use `useBeforeUnload` as your reference.

Is this hook already dynamic in any data? we should make sure that this hook can be reuse in any other business logics.

2024-11-09 03:15 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/SalesManagement/All-Sale.tsx
Can you prevent creating such file name like `All-Sale.tsx` ? I already said this multiple times.

2024-11-09 03:15 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/SalesManagement/SalesManagementData.ts
What is `SalesManagementData.ts` can we use appropriate name for this ? please think twice before creating one.

2024-11-09 03:15 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/SalesManagement/SalesManagementData.ts
> +
Please change your constant naming here use appropriate naming convention

2024-11-09 11:15 UTC, JMSevilla approved these changes

2024-11-09 12:11 UTC, JMSevilla requested changes

2024-11-09 12:11 UTC, JMSevilla commented on packages/core-library/hooks/usePeriodTime.ts
> +/**
This comment must be before the hook function , `types` and `interface` should be at the top level

2024-11-09 12:51 UTC, acostales08 approved these changes

2024-11-09 13:44 UTC, be3jaay approved these changes

2024-11-10 05:12 UTC, JMSevilla approved these changes

2024-11-10 07:43 UTC, merged