@86eqmv2em #Delivery-board-request-ContactUs-adjustments
NCLEXPower/nclexpower_turbo pull request #424
Opened 2024-11-06 16:24 UTC by acostales08

![image](https://github.com/user-attachments/assets/b0b9824e-7e57-459b-a0d0-563e56c13912)

2024-11-07 04:21 UTC, BryanPalad requested changes

2024-11-07 04:21 UTC, BryanPalad commented on apps/web-customer/src/pages/shared/Page.tsx
> +  // }
Revert the if Maintenance block, remove the comments

2024-11-07 04:21 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/ContactBlock/ContactForm.tsx
> +import { ControlledSelectField } from "core-library/components/Textfield/SelectTextfield";
Also include the TextField/SelectField on index export and include ControlledSelectField to core-library/components import

2024-11-07 15:32 UTC, be3jaay approved these changes

2024-11-08 12:59 UTC, BryanPalad approved these changes

2024-11-08 12:59 UTC, DropitupQwerty requested changes

2024-11-08 12:59 UTC, DropitupQwerty commented on apps/web-customer/src/components/blocks/ContactBlock/ContactForm.tsx
> +  const sample = [
Can you move this in constant ?

2024-11-11 13:29 UTC, closed without merging