@86eqmv2em #DeliveryBoardRequest-ContactUs-section-adjustments
NCLEXPower/nclexpower_turbo pull request #439
Opened 2024-11-11 13:39 UTC by acostales08

![image](https://github.com/user-attachments/assets/0e3c16f7-7333-4ba3-9e05-cea3a9ccb115)

2024-11-11 15:28 UTC, LizterBabael requested changes

2024-11-11 15:28 UTC, LizterBabael commented on packages/core-library/types/constant.ts
> +export const DEFAULT_PHONE_COUNTRY_CODE = "US"; //we can change this to united states default phone cc
you can remove the comment since u already changed it

2024-11-12 04:28 UTC, BryanPalad approved these changes

2024-11-12 12:01 UTC, LizterBabael approved these changes

2024-11-13 14:49 UTC, JezChristian approved these changes

2024-11-17 11:32 UTC, JMSevilla approved these changes

2024-11-17 13:07 UTC, merged