Feature/86eqmv432/dbr case study management bug fixes
NCLEXPower/nclexpower_turbo pull request #452
Opened 2024-11-15 18:10 UTC by DropitupQwerty

2024-11-16 03:31 UTC, JezChristian requested changes
I did find some minor comments.

It would be nice if you can add 
/**
 * Property of the NCLEX Power.
 * Reuse as a whole or in part is prohibited without permission.
 * Created by the Software Strategy & Development Division
 */
 
 and I noticed some of the components are directly imported, kindly import them from our components.

2024-11-16 03:31 UTC, JezChristian commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/casestudy/CaseStudyCreation/components/BackgroundInfoTab.tsx
>  import { GenericSelectField } from "../../../../../../../../../../../../../../../components/Textfield/GenericSelectField";
Component is directly imported

2024-11-16 03:31 UTC, JezChristian commented on packages/core-library/components/RichTextEditor/EditorButtonGroup.tsx
>    return menus.map((button, index) => (
does objects in menus doesn't have id? It was suggested to use the id from your array instead from the mapping index.

2024-11-16 04:20 UTC, DropitupQwerty commented on packages/core-library/components/RichTextEditor/EditorButtonGroup.tsx
>    return menus.map((button, index) => (
This array is immutable and don't have any id to use

2024-11-16 06:03 UTC, JezChristian approved these changes

2024-11-16 12:58 UTC, BryanPalad approved these changes

2024-11-16 13:40 UTC, LizterBabael approved these changes

2024-11-16 15:14 UTC, JMSevilla requested changes

2024-11-16 15:14 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/simulator/steps/content/casestudy/CaseStudyCreation/CreateCaseStudyQuestion.tsx
> +  const BGInfoTabs = useMemo(() => generateInfoTabs(), []);
When using `useMemo` we should have dependency so if the there is some changes from the dependencies then it will re-memoize the function.

2024-11-17 14:22 UTC, JMSevilla approved these changes

2024-11-17 14:30 UTC, merged