@86eqdaxxn #rePR of reusable delete typing Custom DeleteModal with Dy…
NCLEXPower/nclexpower_turbo pull request #455
Opened 2024-11-17 14:02 UTC by acostales08

rePR this close before due to failure of deploy

2024-11-18 13:06 UTC, JezChristian approved these changes

2024-11-19 13:01 UTC, JMSevilla requested changes

2024-11-19 13:01 UTC, JMSevilla commented on packages/core-library/components/Dialog/DialogFormBlocks/DeleteModal/DeleteModalForm.tsx
> +export const DeleteConfirmationForm: React.FC<Props> = ({
Overall, the DeleteConfirmationForm component is well-structured and leverages react-hook-form effectively with yup validation. However, there are some areas for improvement that can enhance the clarity, performance, and maintainability of this code:

1. Form Control Improvements
Instead of calling setValue manually, consider initializing the form with defaultValues when calling useForm. This keeps the form initialization logic more declarative and reduces reliance on side effects.

const form = useForm<DeleteConfirmationType>({
  mode: "all",
  resolver: yupResolver(DeleteConfirmationSchema),
  defaultValues: {
    id: data.id,
    text: data.text,
  },
});

2. Redundant Box Wrappers
The outer <Box> components for layout are well-organized, but some nesting is redundant (e.g., the icon and surrounding <Box>). Simplify these where possible to reduce DOM complexity.

it should be look like this 

<Box
  display="flex"
  flexDirection="column"
  alignItems="center"
  gap="24px"
  height="100%"
  width="100%"
>
  <EvaIcon
    name="alert-triangle-outline"
    width={75}
    height={75}
    ariaHidden
    fill="#D44333"
  />
  ...
</Box>

2024-11-21 08:31 UTC, JMSevilla approved these changes

2024-11-21 12:09 UTC, merged