@86eqmv2em #Contact us adjustment and contact creation api integration
NCLEXPower/nclexpower_turbo pull request #464
Opened 2024-11-20 15:52 UTC by DropitupQwerty

2024-11-20 17:46 UTC, JMSevilla requested changes

2024-11-20 17:46 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/ContactBlock/ContactFormBlock.tsx
> +        `There was an error submitting your message: ${(error as Error).message}`,
as customer we don't want to see the cause of error

2024-11-20 17:46 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/ContactBlock/ContactFormBlock.tsx
> +        "Your message has been received. Thank you",
"Your message has been sent. Please check your email for your reference number"

2024-11-20 17:46 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/ContactBlock/ContactFormBlock.tsx
>    const toast = useExecuteToast();
Kindly use simplified function created by bryan instead of executeToast.

2024-11-20 18:52 UTC, acostales08 approved these changes

2024-11-21 08:32 UTC, JMSevilla approved these changes

2024-11-21 09:14 UTC, JezChristian approved these changes

2024-11-21 11:15 UTC, merged