@faeture/86eqj2n7j/Search-bar-border-focus-alignment
NCLEXPower/nclexpower_turbo pull request #483
Opened 2024-11-23 13:56 UTC by Tine0814

![image](https://github.com/user-attachments/assets/eb48b592-6437-4a16-b685-43314f411ce2)
![image](https://github.com/user-attachments/assets/ee232439-8e8a-4c7b-a56b-45f04fede670)

2024-11-23 14:42 UTC, JezChristian requested changes
Double check the imported components like the button

2024-11-23 15:00 UTC, JMSevilla requested changes

2024-11-23 15:40 UTC, acostales08 approved these changes

2024-11-25 07:04 UTC, JMSevilla approved these changes

2024-11-25 07:04 UTC, merged