@86eqqnjnf #Maintenance Mode Integration
NCLEXPower/nclexpower_turbo pull request #497
Opened 2024-11-29 07:21 UTC by JezChristian

![brave_r4uLG5e6Qq](https://github.com/user-attachments/assets/e86776fc-b2c3-4ae9-9877-2d3697ccaa9b)

2024-11-30 04:18 UTC, JMSevilla requested changes

2024-11-30 04:18 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/constants/constants.ts
> +export const EnvironmentList: EnvironmentItem[] = [
Is this necessary to stay on our codebase?

2024-11-30 04:18 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/ChooseSettingsTypeStep.tsx
> +  | "WEBCMaintenanceMode";
change to `MaintenanceMode`

2024-11-30 04:18 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/EnvironmentSelection.tsx
> +  return isLoading ? (
loading state should be separated from the actual render

2024-11-30 04:18 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/EnvironmentSelection.tsx
> +interface StatusButtonProps {
We should prevent create another block of component with interfaces within 1 block of code please follow best practices.

2024-11-30 04:18 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/EnvironmentSelection.tsx
> +const StatusButton = ({ onSubmit, data, Env }: StatusButtonProps) => {
You can create a separate file for this block of code.

2024-11-30 04:18 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/WCMaintenanceMode.tsx
> +export const WCMaintenanceMode: React.FC<Props> = ({
use appropriate name remove `WC`

2024-11-30 04:18 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/WCMaintenanceMode.tsx
> +      window.location.reload();
Why we are using window.location.reload?

2024-11-30 04:18 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/component/EnvTextConfirmation.tsx
> +export const EnvTextConfirmation = ({ Env, onSubmit }: Props) => {
Are we supposed to create a reusable component that can be used by other logic ? we shouldn't create component folder within the stepper. 

Also kindly use appropriate name

2024-11-30 04:18 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/component/EnvTextConfirmation.tsx
> +      <ControlledTextField
Try using our `<TextField />`

2024-11-30 04:18 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/component/EnvTextConfirmation.tsx
> +      <Button
add loading state property on this button

2024-11-30 04:18 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/content/SettingsManagement.tsx
> +    .oneOf(["DBEXCEL", "QM", "IARM", "WEB_C"])
use Appropriate name

2024-11-30 04:18 UTC, JMSevilla commented on packages/core-library/tests/components/MaintenanceMode/WCMaintenanceMode.test.tsx
> +import { renderHook } from "../../common";
you are creating a test for hook but the file path isn't complimenting. be more detailed when creating files

create `hooks` folder name your file properly according to your code

2024-11-30 04:18 UTC, JMSevilla commented on packages/core-library/tests/components/MaintenanceMode/EnvironmentSelection.test.tsx
> +  it("renders the form when isLoading is false", () => {
lack of testing based on your implementation you need more testing scenarios to increase the coverage

2024-11-30 10:13 UTC, JezChristian commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/constants/constants.ts
> +export const EnvironmentList: EnvironmentItem[] = [
Yes, I currently use and map that in the Maintenance Mode Page instead of hard coding each button

2024-11-30 12:35 UTC, JezChristian commented on packages/core-library/api/web/web-api-backoffice.ts
> +      environments: params,
Yes, as an array of string

2024-12-02 03:31 UTC, JMSevilla requested changes

2024-12-02 03:31 UTC, JMSevilla commented on packages/core-library/api/web/web-api-backoffice.ts
> +      environments: params,
We shouldn't since we already passing the environment value fixed in headers please refer to `useApi`

2024-12-02 03:31 UTC, JMSevilla commented on packages/core-library/core/business/dates.ts
> +    timeZone: "Asia/Singapore",
I guess we shouldn't use generic code when defining timeZone, we already have a function to call timeZone dynamically please refer to `useApi`

2024-12-02 03:31 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/MaintenanceMode.tsx
> +    return <div>Loading Contents</div>;
Are we not using a page loader for WB ?

2024-12-02 12:33 UTC, be3jaay requested changes

2024-12-02 12:33 UTC, be3jaay commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/EnvironmentSelection.tsx
> +import TaskAltOutlinedIcon from "@mui/icons-material/TaskAltOutlined";
maybe we can used the icon from eva if it is not applicable, we can make this one.
```suggestion
   import { GppMaybeOutlinedIcon as GppOutlineIcon, TaskAltOutlinedIcon as TaskOutlinedIcon} from '@mui/icons-material';
```

2024-12-02 12:33 UTC, be3jaay commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/EnvironmentSelection.tsx
> +import { Card } from "../../../../../../../../../components";
import the StatusButton here
```suggestion
import { Card, StatusButton } from "../../../../../../../../../components";
```

2024-12-02 12:33 UTC, be3jaay commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/EnvironmentSelection.tsx
> +import { StatusButton } from "../../../../../../../../../components/Button/StatusButton";
Add this to index.ts component

2024-12-02 12:33 UTC, be3jaay commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/MaintenanceMode.tsx
> +          isLoading={isLoading}
add disabled={isLoading}

2024-12-02 12:33 UTC, be3jaay commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/validation.ts
> +  activeField: string | undefined | null
would there be an issue if we use this?
```suggestion
  activeField?: string | null
```

2024-12-02 12:33 UTC, be3jaay commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/EnvironmentSelection.tsx
> +                    loading={isLoading}
add disabled={isLoading}

2024-12-02 13:24 UTC, JezChristian commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/MaintenanceMode.tsx
> +          isLoading={isLoading}
disabled is implemented in the actual button under EnvironmentSelection

2024-12-02 14:04 UTC, be3jaay approved these changes

2024-12-02 15:26 UTC, DropitupQwerty approved these changes

2024-12-02 15:26 UTC, DropitupQwerty commented on packages/core-library/components/Textfield/ConfirmationTextfield.tsx
> +  onSubmit: (value: any) => void;
any

2024-12-02 15:26 UTC, DropitupQwerty commented on packages/core-library/components/Textfield/ConfirmationTextfield.tsx
> +  const textToType = `${item.toUpperCase()}`;
why implement like this if you can just do this 

item.toUpperCase()

2024-12-02 15:26 UTC, DropitupQwerty commented on packages/core-library/components/Textfield/ConfirmationTextfield.tsx
> +export type EnvironmentFormType = {
Contains 2 types in a single file

2024-12-02 15:26 UTC, DropitupQwerty commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/EnvironmentSelection.tsx
> +  const [, setStatus] = useAtom(SelectedConfirmationObj);
why this need to be separated in useAtom and useAtomValue. When you can use the [set,get] in useAtom

2024-12-02 15:26 UTC, DropitupQwerty commented on packages/core-library/system/app/internal/blocks/Hub/Settings/SettingsManagement/steps/MaintenanceMode/MaintenanceMode.tsx
> +import useMaintenanceMode from "../../../../../../../../../hooks/useMaintenanceMode";
directly accessing the hook

2024-12-03 10:03 UTC, JMSevilla approved these changes

2024-12-03 10:17 UTC, merged