@86eqxnrqc #Fix customer creation minor bugs
NCLEXPower/nclexpower_turbo pull request #511
Opened 2024-12-07 04:51 UTC by BryanPalad

2024-12-10 15:50 UTC, acostales08 approved these changes

2024-12-11 02:58 UTC, JMSevilla requested changes

2024-12-11 02:58 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Account/Registration/validation.ts
> +      /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/,
You can place this regex to `fp-regex.ts` but can you also please change the file name from `fp-regex.ts` to `regex.ts` 

note : once changed please check for any implementation that relates to `fp-regex.ts`

2024-12-11 02:58 UTC, JMSevilla commented on packages/core-library/components/forms/TextField.tsx
> +  isRegister?: boolean;
This property is being logged as error from the next application as it has a uppercase on it. can you change this to `isregister`

2024-12-11 09:50 UTC, JMSevilla requested changes

2024-12-11 09:50 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Account/Registration/validation.ts
> +    .matches(EMAIL_REGEX, "Please provide a valid email")
Sorry I overlook this one, we have a built-in function from yup we can use instead to use regex

kindly use .email()

2024-12-11 09:50 UTC, JMSevilla commented on packages/core-library/utils/regex.ts
> +export const EMAIL_REGEX = /^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$/;
Remove this since it is not necessary

2024-12-11 10:04 UTC, BryanPalad commented on packages/core-library/system/app/internal/blocks/Account/Registration/validation.ts
> +    .matches(EMAIL_REGEX, "Please provide a valid email")
The .email() function from Yup was previously implemented, but it still accepts emails like example@gmail without a .com or valid domain, making the validation inconsistent and allowing registration to proceed without a valid email. That's why I've used custom email regex.

2024-12-11 10:12 UTC, JMSevilla commented on packages/core-library/system/app/internal/blocks/Account/Registration/validation.ts
> +    .matches(EMAIL_REGEX, "Please provide a valid email")
In that case can you combine both .email() & regex

2024-12-11 10:13 UTC, BryanPalad commented on packages/core-library/system/app/internal/blocks/Account/Registration/validation.ts
> +    .matches(EMAIL_REGEX, "Please provide a valid email")
Copy that

2024-12-11 10:32 UTC, JMSevilla approved these changes

2024-12-11 12:25 UTC, JezChristian approved these changes

2024-12-11 12:48 UTC, merged