Feature/86eqrqnh7/wc billing summary UI
NCLEXPower/nclexpower_turbo pull request #515
Opened 2024-12-08 14:57 UTC by BryanPalad

2024-12-10 16:18 UTC, JMSevilla requested changes

2024-12-10 16:18 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HubBlocks/BillingSummaryBlock/BillingSummaryBlock.tsx
> +const columns = [
Since you have mock data , can you transfer this to BillingSummaryMock

2024-12-10 16:18 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HubBlocks/BillingSummaryBlock/BillingSummaryBlock.tsx
> +  // const { data, isLoading } = businessQueryGetBillingSummary(['getBillingSummary']);
Don't forget to use standard api call instead of using react query to prevent this code for refactoring

2024-12-10 16:18 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HubBlocks/BillingSummaryBlock/BillingSummaryBlock.tsx
> +  useEffect(() => {
For the entire logic on your BillingSummaryBlock you can create a hook.

2024-12-10 16:18 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HubBlocks/BillingSummaryBlock/BillingSummaryBlock.tsx
> +            <OrderSummaryBlock selectedRow={selectedRow} />
Is this normal ? implementing it twice ?

2024-12-10 16:18 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HubBlocks/BillingSummaryBlock/OrderDetailsBlock.tsx
> +const orderDetailTitles = ["dateTime", "payment", "receiptNumber", "purchase", "amount", "validity", "promo"];
This can also be part of your mock data, when creating mock centralized them so once we need to remove those. We can remove it once.

2024-12-10 16:18 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/HubBlocks/BillingSummaryBlock/OrderSummaryBlock.tsx
> +            Name: <span className="ml-2">Albert Rivera</span>
This should be dynamic ready create a mock to feed on this content.

2024-12-11 10:59 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/HubBlocks/BillingSummaryBlock/BillingSummaryBlock.tsx
> +const columns = [
Noted

2024-12-11 11:01 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/HubBlocks/BillingSummaryBlock/OrderDetailsBlock.tsx
> +const orderDetailTitles = ["dateTime", "payment", "receiptNumber", "purchase", "amount", "validity", "promo"];
Noted

2024-12-11 11:08 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/HubBlocks/BillingSummaryBlock/BillingSummaryBlock.tsx
> +            <OrderSummaryBlock selectedRow={selectedRow} />
Renamed the state name to avoid confusion.

2024-12-11 12:06 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/HubBlocks/BillingSummaryBlock/BillingSummaryBlock.tsx
> +  // const { data, isLoading } = businessQueryGetBillingSummary(['getBillingSummary']);
Will add this to the comment for future refence on api fetching.

2024-12-11 12:21 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/HubBlocks/BillingSummaryBlock/BillingSummaryBlock.tsx
> +  useEffect(() => {
Noted

2024-12-11 12:47 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/HubBlocks/BillingSummaryBlock/OrderSummaryBlock.tsx
> +            Name: <span className="ml-2">Albert Rivera</span>
Done creating mockData for this, will use `useSensitiveInformation` once already fix on wc side.

2024-12-12 12:01 UTC, JezChristian requested changes

2024-12-12 12:51 UTC, JezChristian approved these changes

2024-12-13 11:04 UTC, JMSevilla approved these changes

2024-12-13 13:11 UTC, merged