@86eqzwj2x #added security block for settings management
NCLEXPower/nclexpower_turbo pull request #545
Opened 2024-12-14 13:47 UTC by adrian92612

2024-12-18 11:48 UTC, be3jaay requested changes

2024-12-18 11:48 UTC, be3jaay commented on apps/web-customer/src/components/blocks/HubBlocks/Settings/AccountBlock/AccountBlock.tsx
>  interface AccountProps {
Always add spacing between import and interface.

2024-12-18 11:48 UTC, be3jaay commented on apps/web-customer/src/components/blocks/HubBlocks/Settings/PlansBlock/PlansBlock.tsx
> +              </>))}
No need for fragment here. just return the PlansCard

2024-12-18 11:48 UTC, be3jaay commented on apps/web-customer/src/components/blocks/HubBlocks/Settings/SecurityBlock/SecurityBlock.tsx
> +import { Box, Switch, SxProps } from "@mui/material";
We can use our own Switch component from the core-library

2024-12-18 11:48 UTC, be3jaay commented on apps/web-customer/src/components/blocks/HubBlocks/Settings/SecurityBlock/SecurityBlock.tsx
> +import { Button, EvaIcon } from "core-library/components";
```suggestion
import { 
Button, 
EvaIcon,
TextField,
Switch,
} from "core-library/components";
```

2024-12-18 11:48 UTC, be3jaay commented on apps/web-customer/src/components/blocks/HubBlocks/Settings/PlansBlock/PlansBlock.tsx
> +            <div className='border-b w-full  border-[#0F2A71] border-opacity-50'>
```suggestion
            <div className='border-b w-full  border-darkBlue border-opacity-50'>
```

2024-12-18 12:57 UTC, adrian92612 commented on apps/web-customer/src/components/blocks/HubBlocks/Settings/PlansBlock/PlansBlock.tsx
> +              </>))}
Noted sir, removed the fragments.

2024-12-18 12:57 UTC, adrian92612 commented on apps/web-customer/src/components/blocks/HubBlocks/Settings/SecurityBlock/SecurityBlock.tsx
> +import { Box, Switch, SxProps } from "@mui/material";
Noted, used our own SwitchButton.

2024-12-18 12:58 UTC, adrian92612 commented on apps/web-customer/src/components/blocks/HubBlocks/Settings/SecurityBlock/SecurityBlock.tsx
> +import { Button, EvaIcon } from "core-library/components";
Imports updated

2024-12-18 13:11 UTC, BryanPalad approved these changes

2024-12-19 13:49 UTC, be3jaay approved these changes

2024-12-29 02:04 UTC, merged