Feature/86eqxm068 go live coming soon
NCLEXPower/nclexpower_turbo pull request #558
Opened 2024-12-17 07:00 UTC by be3jaay

2024-12-17 07:38 UTC, JMSevilla commented on apps/web-customer/src/pages/coming-soon.tsx
> +const ComingSoon: React.FC = () => {
Coming soon page shouldn't be a page since this will work as `Maintenance` mode this should be render with the combination of SSR

2024-12-18 11:51 UTC, JezChristian approved these changes

2024-12-18 12:18 UTC, BryanPalad requested changes

2024-12-18 12:20 UTC, be3jaay commented on apps/web-customer/src/components/blocks/ComingSoonBlock/ComingSoon.tsx
> +} from "@mui/icons-material";
Upon checking on eva, there's no InstagramIcon so i decided to just use every icon on mui to have consistency.

2024-12-18 12:29 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/ComingSoonBlock/ComingSoon.tsx
> +} from "@mui/icons-material";
Ohhh I see. Noted

2024-12-18 12:42 UTC, JMSevilla requested changes

2024-12-18 12:42 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/ComingSoonBlock/ComingSoon.tsx
> +} from "@mui/icons-material";
I believe this go live implementation does have figma right ? can you do this ff:

1. Go to figma (find the go live design)
2. Find the icons from figma and try to extract them as SVG
3. Create 3 function and paste the svg 

please find this file for example `ErrorFieldIcon.tsx`

2024-12-18 12:42 UTC, JMSevilla commented on packages/core-library/hooks/useCountdown.ts
> +    return days * 86400 + hours * 3600 + minutes * 60 + seconds;
Are these already tested in simulator ? since I believe we are using the same function

2024-12-18 13:19 UTC, be3jaay commented on packages/core-library/hooks/useCountdown.ts
> +    return days * 86400 + hours * 3600 + minutes * 60 + seconds;
![image](https://github.com/user-attachments/assets/6e8a1b91-4972-486e-ae9c-005555f374f1)
working parin man

2024-12-18 14:45 UTC, BryanPalad approved these changes

2024-12-20 08:15 UTC, JMSevilla requested changes

2024-12-20 08:15 UTC, JMSevilla commented on apps/web-customer/src/components/blocks/ComingSoonBlock/ComingSoonData.ts
> +export const dateData = [{
Instead of creating separate file for this small changes you can add this in coming soon block

2024-12-20 09:38 UTC, JMSevilla approved these changes

2024-12-20 09:40 UTC, merged