@86eqxx86x #added Program list skeleton loaders for List and Grid view
NCLEXPower/nclexpower_turbo pull request #569
Opened 2024-12-20 02:38 UTC by adrian92612

<img width="1440" alt="Screenshot 2024-12-20 at 10 35 18 AM" src="https://github.com/user-attachments/assets/2435feb9-aee4-45ae-9c36-ccf836a6fc24" />
<img width="1440" alt="Screenshot 2024-12-20 at 10 35 39 AM
" src="https://github.com/user-attachments/assets/cb0f6f28-2ff7-46d4-acde-69d9b0045cd5" />

https://app.clickup.com/t/86eqxx86x

2024-12-20 08:31 UTC, JMSevilla requested changes

2024-12-20 08:31 UTC, JMSevilla commented on apps/web-customer/src/components/Skeleton/ProgramGridSkeleton.tsx
> +import { Box, Skeleton } from "@mui/material";
Try using our existing skeleton loader component `AnimatedSkeleton`

2024-12-20 08:31 UTC, JMSevilla commented on apps/web-customer/src/components/Skeleton/ProgramListSkeleton.tsx
> +interface ControlledAccordionSkeletonProps {
Please use appropriate naming for interface it should be related with the component you are creating.

2024-12-20 08:31 UTC, JMSevilla commented on apps/web-customer/src/components/Skeleton/ProgramGridSkeleton.tsx
> +export const ProgramGridSkeleton: React.FC<ProgramGridSkeletonProps> = ({
For code improvement and readability

Create a ProgramSkeletonLoaderContainer

1. Inside the container create 2 separate component for list and grid loader
2. Create a conditional render to render both in 1 container
3. Other way to make your code clean retain both files inside the folder programs inside programs folder we should see ProgramSkeletonLoaderContainer, ProgramGridSkeleton and ProgramListSkeleton

Usage:
Use the skeleton loader container and pass props for loader style if either grid or list

2024-12-20 08:39 UTC, be3jaay requested changes

2024-12-20 08:39 UTC, be3jaay commented on apps/web-customer/src/pages/hub/programs/body-systems/index.tsx
> +import React, { Suspense } from "react";
Remove the suspense if you didn't use it.

2024-12-20 08:39 UTC, be3jaay commented on apps/web-customer/src/pages/hub/programs/body-systems/index.tsx
> +    <>
Remove unnecessary fragment

2024-12-20 08:39 UTC, be3jaay commented on apps/web-customer/src/components/Skeleton/ProgramListSkeleton.tsx
> +export const ProgramListViewSkeleton: React.FC<
File name should also be our name here, which should be ProgramListSkeleton.

2024-12-21 04:27 UTC, be3jaay approved these changes

2024-12-21 11:50 UTC, BryanPalad approved these changes

2025-01-02 16:18 UTC, JMSevilla approved these changes

2025-01-02 16:22 UTC, merged