@86eqxm05r #Redesigned maintenance mode page for web customer
NCLEXPower/nclexpower_turbo pull request #584
Opened 2024-12-29 07:50 UTC by christyacanete

Maintenance mode revamp for web customer app.

2024-12-29 12:35 UTC, BryanPalad requested changes

2024-12-29 12:35 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/MaintenanceBlock/MaintenanceForm.tsx
> +      {/* Construction worker image */}
You can remove the comment.

2024-12-29 12:35 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/MaintenanceBlock/MaintenanceForm.tsx
> +      {/* Content */}
Remove comment also

2024-12-29 12:35 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/MaintenanceBlock/MaintenanceForm.tsx
> +          {/* Title */}
Same comment

2024-12-29 12:35 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/MaintenanceBlock/MaintenanceForm.tsx
> +            We’re Under <span className="text-[#0F2A71]">Maintenance</span>
Instead of using #0F2A71 as color you can just use `text-darkBlue` you can refer other styles from our tailwind.ts configuration.

2024-12-29 12:35 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/MaintenanceBlock/MaintenanceForm.tsx
> +          {/* Description */}
Remove comment

2024-12-29 12:35 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/MaintenanceBlock/MaintenanceForm.tsx
> +          <p className="max-w-full sm:max-w-[300px] md:max-w-[350px] xl:max-w-[450px] 2xl:max-w-[500px] mt-4 xl:mt-6 font-ptSans font-[400] text-[14px] sm:text-[14px] md:text-[16px] lg:text-[16.4px]
change text-#969696 to `text-darkGray`

2024-12-29 12:35 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/MaintenanceBlock/MaintenanceForm.tsx
> +          {/* Contact form */}
Remove comment

2024-12-29 12:35 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/MaintenanceBlock/MaintenanceForm.tsx
> +          {/* Contact us */}
Remove comment

2024-12-29 12:35 UTC, BryanPalad commented on apps/web-customer/src/components/blocks/MaintenanceBlock/MaintenanceForm.tsx
> +                className="font-[700] underline text-[#0F2A71]"
Change to `text-darkBlue`

2024-12-30 08:22 UTC, christyacanete commented
Attached are screenshots of the page displayed on various screen sizes for your review.

![Xa2mB4fchW](https://github.com/user-attachments/assets/be3303f2-fa50-4216-b282-def8a06a38a7)
![chrome_vGTy2aYaAx](https://github.com/user-attachments/assets/ae3cb13b-6e6d-4ebd-82d4-7cffb5da557a)
![chrome_I1R0L6Sy5d](https://github.com/user-attachments/assets/be6a85ba-e912-4d7e-8325-c123eb778661)
![chrome_3vMBM2VqJp](https://github.com/user-attachments/assets/01efca03-9f86-4654-9931-24b507b4874c)

2024-12-30 09:05 UTC, JMSevilla commented on package.json
> +  "dependencies": {
Is this added intentionally or it added automatically?

2024-12-30 11:01 UTC, BryanPalad approved these changes

2024-12-30 11:48 UTC, christyacanete commented on package.json
> +  "dependencies": {
I think automatically sir. I haven't added anything on this file.

2025-01-02 09:34 UTC, DropitupQwerty approved these changes

2025-01-03 14:17 UTC, nyolarraklay approved these changes

2025-01-04 03:05 UTC, JezChristian approved these changes

2025-01-04 06:10 UTC, merged